# application.properties for local dev
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ddmerchant}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ddmerchant}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ddmerchant}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics
